main/urls.py
from django.urls import path
from .views import create_list, home, invite_members,manage_list,create_item, revoke_access,show_invites,accept_invite,decline_invite,manage_members

app_name = "main"

urlpatterns = [
        path("", home, name="home"),
        path("manage/<int:list_id>", manage_list, name="manage"),
        path("invites/", show_invites, name="show_invites"),
        path("invites/<int:invite_id>/accept", accept_invite, name="accept_invite"),
        path("invites/<int:invite_id>/decline", decline_invite,name="decline_invite"),
        path("list/create/", create_list, name="create_list"),
        path("list/<int:list_id>/create_item", create_item, name="create_item"),
        path("list/<int:list_id>/invite_members", invite_members, name="invite_members"),
        path("list/<int:list_id>/members", manage_members, name="manage_members"),
        path("list/<int:list_id>/members/<str:username>/revoke", revoke_access, name="revoke_access")
    ]

toXdo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('auth/', include("users.urls"))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class TodoList(models.Model):
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="owned_lists"
    )
    name = models.CharField(max_length=100)
    members = models.ManyToManyField(User, related_name="lists")
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    @property
    def modified_at(self):
        try:
            time = self.items.order_by("modified_at")[0].modified_at
        except:
            time = self.created_at
        return time

    @property
    def stats(self):
        x = self.items
        return f"Pending : {x.filter(status="P").count()} In-Progress: {x.filter(status="I").count()} Completed : {x.filter(status="C").count()}"
        


class TodoListItem(models.Model):
    STATUS_CHOICES = {"P": "Pending", "I": "In-Progress", "C": "Completed"}
    PRIORITY_CHOCIES = {"H" : "High", "M": "Medium", "L": "Low"}
    todo_list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="items"
    )
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="P")
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOCIES, default="M")


class TodoInvitation(models.Model):
    STATUS_CHOICES = {"P": "Pending", "A": "Accepted", "R": "Rejected"}
    todo_list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="invites"
    )
    recipient = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="invites"
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="P")

main/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import TodoInvitation, TodoList, TodoListItem

# Create your views here.
@login_required
def home(request):
    user = request.user

    lists = user.lists.all()
    return render(request, "main/home.html", {"lists": lists})

@login_required
def manage_list(request, list_id):
    try:
        todo_list = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        messages.error(request, "No such list exists")
        return redirect("main:home")
    if request.method == "GET":
            
        if request.user not in todo_list.members.all():
            messages.error(request, "You don't have access to this list")
            return redirect("main:home")

        context = {"list": todo_list, "owner":(request.user == todo_list.owner)}

        return render(request, "main/manage.html", context)
    if request.method == "POST":
       updated_keys = [int(k.split("_")[-1]) for k in request.POST.dict().keys() if "csrf" not in k and k.split("_")[-1].isdigit()]
       items = [i.id  for i in todo_list.items.all()]

       if updated_keys == items:
            for key in updated_keys:
               new_status=request.POST["status_select_" + str(key)]
               if new_status != todo_list.items.get(id=key):
                   item = todo_list.items.get(id=key)
                   item.status = new_status
                   item.save()
            messages.success(request, "Updated Successfully!")
            return redirect("main:manage", list_id=list_id)
       else:
           messages.error(request,"Invalid Request!")
           return redirect("main:manage", list_id=list_id)


@login_required
def create_list(request):
    if request.method =="POST":
        name = request.POST["name"]
        owner = request.user
        try:
            created_list = TodoList.objects.create(owner=owner, name=name)
            created_list.members.add(owner)
            messages.success(request, "Created List Successfully!")
            return redirect("main:manage", list_id=created_list.id)
        except:
            messages.error(request,"Failed to create list")
            return redirect("main:create_list")
    return render(request, "main/create_list.html")

@login_required
def create_item(request, list_id):
    try:
        todo_list = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        messages.error(request, "No such list exists")
        return redirect("main:home")
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        priority = request.POST["priority"]
        TodoListItem.objects.create(todo_list = todo_list,title=title,description=description, priority=priority,created_by=request.user)
        return redirect("main:manage", list_id=list_id)
    return render(request, "main/create_item.html")

@login_required
def invite_members(request, list_id):
    try:
        todo_list = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        messages.error(request, "No such list exists")
        return redirect("main:home")

    if not todo_list.owner == request.user:
        messages.error(request, "You don't have access to this page")
        return redirect("main:home")

    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST["username"])

            if user in todo_list.members.all():
                messages.error(request, "User is already a member")
                return redirect("main:invite_members", list_id=list_id)

            if TodoInvitation.objects.filter(recipient=user).exists():
                messages.error(request, "User already invited")
                return redirect("main:invite_members", list_id=list_id)

            TodoInvitation.objects.create(todo_list = todo_list, recipient=user)

            messages.success(request,"User Invited!")
            return redirect("main:invite_members", list_id=list_id)

        except User.DoesNotExist:
            messages.error(request, "No Such User exists")
            return redirect("main:invite_members", list_id=list_id)


    return render(request, "main/invite_members.html")

@login_required
def manage_members(request, list_id):
    try:
        todo_list = TodoList.objects.get(id=list_id)
    except TodoList.DoesNotExist:
        messages.error(request, "No such list exists")
        return redirect("main:home")
    if todo_list.owner != request.user:
        messages.error(request, "You don't have access to this")
        return redirect("main:home")


    members = [{"username": member.username, "items": member.todolistitem_set.filter(todo_list=todo_list)} for member in todo_list.members.exclude(id = request.user.id)]

    return render(request, "main/manage_members.html", {"members": members, "list": todo_list})

@login_required
def revoke_access(request,list_id, username ):
    try:
        todo_list = TodoList.objects.get(id=list_id)
        user = User.objects.get(username=username)
    except TodoList.DoesNotExist:
        messages.error(request, "No such list exists")
        return redirect("main:home")
    except User.DoesNotExist:
        messages.error(request, "No such user exists")
        return redirect("main:home")
    if todo_list.owner == user:
        messages.error(request, "Cannot remove owner from todolist")
        return redirect("main:home")

    if todo_list.owner != request.user:
        messages.error(request, "You don't have access to this")
        return redirect("main:home")

    if not todo_list.members.filter(id = user.id).exists():
        messages.error(request, "User is not part of todolist")
        return redirect("main:home")

    todo_list.members.remove(user)
    messages.success(request, "Removed user!")
    return redirect("main:manage", list_id)



@login_required
def show_invites(request):
    invites = TodoInvitation.objects.filter(recipient=request.user, status="P")

    return render(request, "main/show_invites.html", {"invites" : invites})

@login_required
def accept_invite(request, invite_id):
    try:
        invite= TodoInvitation.objects.get(id=invite_id)
    except TodoInvitation.DoesNotExist:
        messages.error(request, "No such invite exists")
        return redirect("main:show_invites")
    if not invite.recipient == request.user:
        messages.error(request, "You don't have access to this")
        return redirect("main:show_invites")

    invite.todo_list.members.add(request.user)
    invite.status = "A"
    invite.save()
    messages.success(request, "Accepted Invite to {}".format(invite.todo_list.name))
    return redirect("main:home")

@login_required
def decline_invite(request, invite_id):
    try:
        invite= TodoInvitation.objects.get(id=invite_id)
    except TodoInvitation.DoesNotExist:
        messages.error(request, "No such invite exists")
        return redirect("main:show_invites")
    if not invite.recipient == request.user:
        messages.error(request, "You don't have access to this")
        return redirect("main:show_invites")

    invite.status = "D"
    invite.save()
    messages.success(request, "Declined Invite to {}".format(invite.todo_list.name))
    return redirect("main:home")

main/templates/main/base.html
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>toXdo : collaborative todo lists</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	</head>	
	<body>
		<header class="p-3 text-bg-dark">
			<div class="container">
				<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
					<a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
						toXdo
					</a>

					<ul class="nav col-12 col-lg-auto me-lg-auto justify-content-center mb-md-0">
						<li><a href="/" class="nav-link ps-4 pe-2 text-secondary">Home</a></li>
						<li><a href="/list/create" class="nav-link px-2 text-secondary">Create List</a></li>
						<li><a href="/invites" class="nav-link px-2 text-secondary">Team Invites</a></li>
					</ul>


					<div class="text-end">
						{% if request.user.is_authenticated %}
						<a href="/auth/logout" class="btn btn-warning">Logout</a>
						{%else%}
						<a href="/auth/login" class="btn btn-outline-light me-2">Login</a>
						<a href="/auth/register" class="btn btn-warning">Sign-up</a>
						{%endif%}
					</div>
				</div>
			</div>
		</header>
		{% if messages %}
		{% for message in messages %}
		<div class="alert alert-{% if message.tags == 'success' %}success{%else%}danger{%endif%} alert-dismissible fade show" role="alert">
			{{message}} 
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
		{%endfor%}
		{%endif%}
		{%block content%}
		{%endblock%}
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	</body>
</html>

main/templates/main/create_item.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Create TodoList Item</h1>
	<div class="container-fluid py-5">
		<form method="post">
			{% csrf_token %}
			<div class="mb-4 row">
				<label class="col-sm-2 col-form-label">Title</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="title">
				</div>
			</div>
			<div class="mb-4 row">
				<label class="col-sm-2 col-form-label">Description</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="description">
				</div>
			</div>
			<div class="mb-4 row">
				<label class="col-sm-2 col-form-label">Priority</label>
				<div class="col-sm-10">
					<select class="form-select" name="priority">
						<option value="H">High</option>
						<option value="M" selected="">Medium</option>
						<option value="H">Low</option>
					</select>
				</div>
			</div>
			<button type="submit" class="btn btn-success">Create Item</button>
		</form>
	</div>
</div>
{%endblock%}

main/templates/main/create_list.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Create List </h1>
	<div class="container-fluid py-5">
		<form method="post">
			{% csrf_token %}
			<div class="mb-4 ">
				<label class="col-sm-2 col-form-label">Name</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="name">
				</div>
			</div>
			<button type="submit" class="btn btn-success">Create List</button>
		</form>
	</div>
</div>
{%endblock%}

main/templates/main/home.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Your Lists </h1>
	<div class="container-fluid py-5">
		{% for list in lists %}
		<div class="card w-75 mb-3">
			<div class="card-body">
				<h5 class="card-title">{{list.name}}</h5>
				<p class="card-text">{{list.stats}}</p>
			</div>
			<ul class="list-group list-group-flush">
				<li class="list-group-item">Owner: {% if list.owner == request.user%}You{%else%} {{list.owner.username}}'s list{%endif%}</li>
				<li class="list-group-item">Created At: {{list.created_at}}</li>
				<li class="list-group-item">Last Modified: {{list.modified_at}}</li>
			</ul>
			<div class="card-body">
				<a href="{% url "main:manage" list.id %}" class="card-link">Manage</a>
			</div>
		</div>
		{%endfor%}
	</div>
</div>

{%endblock%}

main/templates/main/invite_members.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Invite Members </h1>
	<div class="container-fluid py-5">
		<form method="post">
			{% csrf_token %}
			<div class="mb-4 ">
				<label class="col-sm-2 col-form-label">Username</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="username">
				</div>
			</div>
			<button type="submit" class="btn btn-success">Invite</button>
		</form>
	</div>
</div>
{%endblock%}

main/templates/main/manage.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Manage {{list.name}}</h1>
	{% if owner %}
	<a href="/list/{{list.id}}/invite_members" class="btn btn-warning">Invite Users</a>
	<a href="/list/{{list.id}}/members" class="btn btn-primary">Manage Members</a>
	{%endif%}
	<a href="/list/{{list.id}}/create_item" class="btn btn-success">Create Item</a>
	<form method="post">
		{% csrf_token %}
		<div class="container-fluid py-5">
			{% for item in list.items.all %}
			<div class="card w-75 my-5">
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Title: {{item.title}}</li>
					<li class="list-group-item">Description : {{item.description}}</li>
					<li class="list-group-item">Created By: {{item.created_by.username}} | Priority: {% if item.priority is "H" %}High{%elif item.priority is "M"%} Medium {%else%} Low {%endif%} </li>
				</ul>
				<div class="card-footer">
					<div class="row g-3 align-items-center">
						<div class="col-auto">
							<label for="status_select_{{item.id}}" class="col-form-label">Status : </label>
						</div>
						<div class="col-auto">
							<select class="form-select" name="status_select_{{item.id}}">
								<option value="P" {% if item.status == "P" %}selected="" {%endif%} >Pending</option>
								<option value="I" {% if item.status == "I" %}selected="" {%endif%} >In-Progress</option>
								<option value="C" {% if item.status == "C" %}selected="" {%endif%} >Completed</option>
							</select>
						</div>
					</div>
				</div>
			</div>
			{%endfor%}
		</div>
		<button type="submit" class="btn btn-primary">Update</button>
	</form>
</div>

{%endblock%}

main/templates/main/manage_members.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Members for {{list.name}}</h1>
	<div class="container-fluid py-5">
		{% for member in members %}
		<div class="card w-75 mb-3">
			<div class="card-body">
				<h5 class="card-title">{{member.username}}</h5>
			</div>
				<ul class="list-group list-group-flush">
					{% for item in member.items %}
					<li class="list-group-item">Title: {{item.title}} | Description : {{item.description}}</li>
					{% endfor %}
				</ul>
			<div class="card-body">
				<a href="{% url "main:revoke_access" list.id member.username %}" class="card-link">Revoke Access</a>
			</div>
		</div>
		{%endfor%}
	</div>
</div>

{%endblock%}

main/templates/main/show_invites.html
{%extends "main/base.html" %}
{%block content%}
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
	<h1> Your Invites</h1>
	<div class="container-fluid py-5">
		{% for invite in invites %}
		<div class="card w-75 mb-3">
			<div class="card-body">
				<h5 class="card-title">{{invite.todo_list.name}}</h5>
				<h6 class="card-subtitle">Owner:  {{invite.todo_list.owner.username}}</h6>
			</div>
			<div class="card-body">
				<a href="{% url "main:accept_invite" invite.id %}" class="card-link">Accept</a>
				<a href="{% url "main:decline_invite" invite.id %}" class="card-link">Decline</a>
			</div>
		</div>
		{%endfor%}
	</div>
</div>

{%endblock%}